calculator
romhik76/Hello-world pull request #5
Opened 2021-09-24 10:09 UTC by romhik76

2021-09-29 15:42 UTC, goarchitecture requested changes
ДЗ сдано не полностью, выполнено 1 из 3.
Жду дополнений (затегайте когда будет готово)

+ exe файлов не должно быть в гите

2021-09-29 15:42 UTC, goarchitecture commented on task_2/calculator_S.go
> +	{
лишний scope

2021-09-29 15:42 UTC, goarchitecture commented on task_2/calculator_numbers.go
> +	fmt.Printf("S(площадь фигуры) равна: %f\n", a*b)
программа делает тоже самое что и предыдущая. Условие было на 3 разных задания

2021-09-30 06:23 UTC, romhik76 reviewed
@goarchitecture 
выполнил еще одно задание из 2ого урока

2021-09-30 06:51 UTC, merged